import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Puts dictated text into whatever app is focused.
///
/// Strategy (same as most dictation tools): stash the clipboard, write our text,
/// synthesize ⌘V, then restore the original clipboard once the paste has landed.
/// Pasting is far more reliable across apps (Electron, browsers, terminals) than
/// AXValue writes or per-character keystrokes.
enum TextInserter {
    /// Info about the text field we're about to paste into, read via Accessibility.
    struct FocusContext {
        var appName: String?
        var bundleID: String?
        /// Up to ~2 characters immediately before the caret, if readable.
        var textBeforeCaret: String?
    }

    static func focusContext() -> FocusContext {
        let app = NSWorkspace.shared.frontmostApplication
        var ctx = FocusContext(appName: app?.localizedName, bundleID: app?.bundleIdentifier, textBeforeCaret: nil)

        let system = AXUIElementCreateSystemWide()
        var focused: CFTypeRef?
        guard AXUIElementCopyAttributeValue(system, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
              let focusedRef = focused, CFGetTypeID(focusedRef) == AXUIElementGetTypeID() else { return ctx }
        let element = focusedRef as! AXUIElement

        var rangeValue: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &rangeValue) == .success,
              let rangeRef = rangeValue, CFGetTypeID(rangeRef) == AXValueGetTypeID() else { return ctx }
        var selection = CFRange()
        guard AXValueGetValue(rangeRef as! AXValue, .cfRange, &selection) else { return ctx }

        if selection.location == 0 {
            ctx.textBeforeCaret = ""
            return ctx
        }
        let start = max(0, selection.location - 2)
        var lookback = CFRange(location: start, length: selection.location - start)
        guard let lookbackValue = AXValueCreate(.cfRange, &lookback) else { return ctx }
        var str: CFTypeRef?
        if AXUIElementCopyParameterizedAttributeValue(
            element, kAXStringForRangeParameterizedAttribute as CFString, lookbackValue, &str) == .success,
           let s = str as? String {
            ctx.textBeforeCaret = s
        }
        return ctx
    }

    /// Pastes `text` into the focused app. Restores the previous clipboard afterwards
    /// when `restoreClipboard` is true.
    static func insert(_ text: String, restoreClipboard: Bool) {
        let pasteboard = NSPasteboard.general
        let saved = restoreClipboard ? snapshot(pasteboard) : nil

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        // Ask clipboard managers not to record this transient write.
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        item.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        pasteboard.writeObjects([item])
        let ourChangeCount = pasteboard.changeCount

        sendCommandV()

        guard let saved else { return }
        // Give the target app time to read the pasteboard before restoring.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            // If something else wrote to the clipboard meanwhile, leave it alone.
            guard pasteboard.changeCount == ourChangeCount else { return }
            pasteboard.clearContents()
            if !saved.isEmpty { pasteboard.writeObjects(saved) }
        }
    }

    static func copyToClipboard(_ text: String) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { original in
            let copy = NSPasteboardItem()
            for type in original.types {
                if let data = original.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private static func sendCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        // Don't let a still-held fn/option leak into the synthesized paste.
        source?.setLocalEventsFilterDuringSuppressionState(
            [.permitLocalMouseEvents, .permitSystemDefinedEvents],
            state: .eventSuppressionStateSuppressionInterval)
        // ⌘V is matched by character, so find the key that types "v" (Dvorak, AZERTY, …).
        let vKey = KeyboardLayout.keyCode(for: "v") ?? CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cgAnnotatedSessionEventTap)
        up?.post(tap: .cgAnnotatedSessionEventTap)
    }
}
